#ifndef QTSHAREDLIB_GLOBAL_H
#define QTSHAREDLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTSHAREDLIB_LIBRARY)
#  define QTSHAREDLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTSHAREDLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSHAREDLIB_GLOBAL_H
